import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame} from '../src/game.mjs';
let createAccountService;
try { ({createAccountService}=await import('../backend/accounts/service.mjs')); } catch(e) { if(e.code!=='ERR_MODULE_NOT_FOUND')throw e; }
const origin='https://game.test', password='testing-password-123';
async function setup(t){assert.equal(typeof createAccountService,'function','account service exists');const app=createAccountService({database:':memory:',origins:[origin]});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());const base=`http://127.0.0.1:${app.server.address().port}`;return async(path,{body,cookie='',site=origin,method=body?'POST':'GET'}={})=>{const r=await fetch(base+path,{method,headers:{origin:site,cookie,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,cookie:r.headers.get('set-cookie')?.split(';')[0],headers:r.headers,data:await r.json()};};}
test('accounts register, hash secrets, authenticate and isolate sessions',async t=>{const call=await setup(t);const a=await call('/register',{body:{username:'CatOne',password}});assert.equal(a.status,201);assert.ok(a.data.recoveryCode);assert.match(a.headers.get('set-cookie'),/HttpOnly/);assert.match(a.headers.get('set-cookie'),/Secure/);assert.equal(a.data.user.username,'catone');assert.equal((await call('/me',{cookie:a.cookie})).data.user.id,a.data.user.id);assert.equal((await call('/register',{body:{username:'catone',password}})).status,409);assert.equal((await call('/login',{body:{username:'catone',password:'wrong-password'}})).status,401);const login=await call('/login',{body:{username:'CATONE',password}});assert.equal(login.data.user.id,a.data.user.id);assert.equal(login.data.user.honorToken,a.data.user.honorToken);assert.ok(!JSON.stringify(login.data).includes(password));assert.equal((await call('/logout',{cookie:login.cookie,body:{}})).status,200);assert.equal((await call('/save',{cookie:login.cookie})).status,401);});
test('cloud save validates schema and uses compare-and-swap across devices',async t=>{const call=await setup(t);const a=await call('/register',{body:{username:'catone',password}}),b=await call('/register',{body:{username:'cattwo',password}});const save={version:6,state:createGame()};assert.equal((await call('/save',{body:{save,revision:0},cookie:a.cookie})).data.revision,1);assert.equal((await call('/save',{body:{save,revision:0},cookie:a.cookie})).status,409);assert.equal((await call('/save',{cookie:b.cookie})).data.save,null);assert.equal((await call('/save',{body:{save:{version:6,state:{}},revision:1},cookie:a.cookie})).status,400);assert.equal((await call('/save',{cookie:a.cookie})).data.revision,1);assert.equal((await call('/save',{body:{save,revision:1},cookie:a.cookie,site:'https://evil.test'})).status,403);});
test('recovery revokes sessions and cannot be reused',async t=>{const call=await setup(t);const a=await call('/register',{body:{username:'recover',password}});assert.equal((await call('/recover',{body:{username:'recover',recoveryCode:'wrong',password}})).status,401);const r=await call('/recover',{body:{username:'recover',recoveryCode:a.data.recoveryCode,password:'new-password-456'}});assert.equal(r.status,200);assert.ok(r.data.recoveryCode);assert.equal((await call('/save',{cookie:a.cookie})).status,401);assert.equal((await call('/login',{body:{username:'recover',password}})).status,401);assert.equal((await call('/login',{body:{username:'recover',password:'new-password-456'}})).status,200);assert.equal((await call('/recover',{body:{username:'recover',recoveryCode:a.data.recoveryCode,password}})).status,401);});
test('password database contains only hashes; sessions expire; wrong account header blocks writes',async t=>{
 assert.ok(createAccountService);let time=100000000;const app=createAccountService({database:':memory:',origins:[origin],now:()=>time});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());const base=`http://127.0.0.1:${app.server.address().port}`;
 const r=await fetch(base+'/register',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({username:'hashcheck',password})}),data=await r.json(),cookie=r.headers.get('set-cookie').split(';')[0];
 const row=app.db.prepare('SELECT * FROM users').get();assert.notEqual(row.password,password);assert.notEqual(row.recovery,data.recoveryCode);assert.match(row.password,/^[a-f0-9]{32}:[a-f0-9]{128}$/);
 assert.equal((await fetch(base+'/save',{headers:{cookie,'x-account-id':'another-account'}})).status,403);
 time+=31*86400000;assert.equal((await fetch(base+'/save',{headers:{cookie}})).status,401);
});
test('login throttles abuse and oversized payloads are rejected',async t=>{const call=await setup(t);assert.equal((await call('/register',{body:{username:'payload',password,extra:'x'.repeat(270000)}})).status,413);for(let i=0;i<19;i++)await call('/login',{body:{username:'?',password:'short'}});assert.equal((await call('/login',{body:{username:'catone',password}})).status,429);});
